<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>just</string>
		<string>justfile</string>
		<string>.justfile</string>
	</array>
	<key>name</key>
	<string>Just-tmLang</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#interpolate</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#scripts</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#assignments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>assignments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.just</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.name.just</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(export[\s]?)?([a-zA-Z_][a-zA-Z0-9_-]*)\s*:?=</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^#[^!].*</string>
					<key>name</key>
					<string>comment.line.just</string>
				</dict>
			</array>
		</dict>
		<key>interpolate</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\{\{</string>
					<key>end</key>
					<string>\}\}</string>
					<key>name</key>
					<string>string.interpolated.just</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(arch|os|os_family|env_var|env_var_or_default)\b</string>
					<key>name</key>
					<string>keyword.control.just</string>
				</dict>
			</array>
		</dict>
		<key>scripts</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#scripts_js</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#scripts_lua</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#scripts_perl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#scripts_ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#scripts_python</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#scripts_shell</string>
				</dict>
			</array>
		</dict>
		<key>scripts_js</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^\s+)(#!)\s*(\S+) (node)\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.italic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>markup.italic</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.embedded.block.javascript</string>
					<key>end</key>
					<string>^$</string>
					<key>name</key>
					<string>markup.fenced_code.block.just</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>scripts_lua</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^\s+)(#!)\s*(\S+) (lua)\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.italic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>markup.italic</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.embedded.block.lua</string>
					<key>end</key>
					<string>^$</string>
					<key>name</key>
					<string>markup.fenced_code.block.just</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.lua</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>scripts_perl</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^\s+)(#!)\s*(\S+) (perl)\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.italic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>markup.italic</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.embedded.block.perl</string>
					<key>end</key>
					<string>^$</string>
					<key>name</key>
					<string>markup.fenced_code.block.just</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.perl</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>scripts_python</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^\s+)(#!)\s*(\S+) (python3?)\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.italic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>markup.italic</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.embedded.block.python</string>
					<key>end</key>
					<string>^$</string>
					<key>name</key>
					<string>markup.fenced_code.block.just</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.python</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>scripts_ruby</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^\s+)(#!)\s*(\S+) (ruby)\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.italic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>markup.italic</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.embedded.block.ruby</string>
					<key>end</key>
					<string>^$</string>
					<key>name</key>
					<string>markup.fenced_code.block.just</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.ruby</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>scripts_shell</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^\s+)(#!)\s*(\S+) ((?&gt;fi|ba|c|k|z)?sh)\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.italic</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>markup.italic</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.embedded.block.shellscript</string>
					<key>end</key>
					<string>^$</string>
					<key>name</key>
					<string>markup.fenced_code.block.just</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.shell</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>`</string>
					<key>end</key>
					<string>`</string>
					<key>name</key>
					<string>string.quoted.triple.just</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.just</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.just</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.just</string>
	<key>uuid</key>
	<string>68027c80-19a7-47f2-8f03-347e783cccf9</string>
</dict>
</plist>
